require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NumberToPhrasesController do

  # This should return the minimal set of attributes required to create a valid
  # NumberToPhrase. As you add validations to NumberToPhrase, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { number: 10 } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NumberToPhrasesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET new" do
    it "assigns a new number_to_phrase as @number_to_phrase" do
      get :new, {}, valid_session
      assigns(:number_to_phrase).should be_a(NumberToPhrase)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created number_to_phrase as @number_to_phrase" do
        post :create, {:number_to_phrase => valid_attributes}, valid_session
        assigns(:number_to_phrase).should be_a(NumberToPhrase)
      end

      it "redirects to the created number_to_phrase" do
        post :create, {:number_to_phrase => valid_attributes}, valid_session
        response.should render_template("spelled_number")
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved number_to_phrase as @number_to_phrase" do
        # Trigger the behavior that occurs when invalid params are submitted
        NumberToPhrase.any_instance.stub(:save).and_return(false)
        post :create, {:number_to_phrase => {  }}, valid_session
        assigns(:number_to_phrase).should be_a(NumberToPhrase)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NumberToPhrase.any_instance.stub(:save).and_return(false)
        post :create, {:number_to_phrase => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end



end
